name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: make test

      - name: Run tests (short mode)
        run: |
          make build-image
          podman run --rm libnvme-go-test go test -v -short

      - name: Build binary
        run: |
          make build-image
          podman run --rm libnvme-go-test go build -v
